# Generated by Django 4.1.7 on 2023-03-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Like New', 'Like New')], default='Good', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='spine_color',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
