# Generated by Django 4.1.7 on 2023-03-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_condition_book_spine_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='spine_colour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('Poor', 'Poor - annotations, dirt, or other wear'), ('Average', 'Average - significant scuffing'), ('Good', 'Good - minimal scuffing'), ('Very Good', 'Very Good - very minor signs of shelf wear, nothing more'), ('Like New', 'Like New - no visible signs of wear')], default='Good', max_length=20),
        ),
    ]
